#!/bin/bash

# AUX1 List
_AUX1_QUERY_FN() {
	_MESSAGE="AUX1 status"
	_PENTAIR_CMD="#AUX1 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX1_ON_FN() {
	_MESSAGE="Turning AUX1 ON"
	_PENTAIR_CMD="#AUX1 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX1_OFF_FN() {
	_MESSAGE="Turning AUX1 OFF"
	_PENTAIR_CMD="#AUX1 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX2 List
_AUX2_QUERY_FN() {
	_MESSAGE="AUX2 status"
	_PENTAIR_CMD="#AUX2 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX2_ON_FN() {
	_MESSAGE="Turning AUX2 ON"
	_PENTAIR_CMD="#AUX2 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX2_OFF_FN() {
	_MESSAGE="Turning AUX2 OFF"
	_PENTAIR_CMD="#AUX2 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX3 List
_AUX3_QUERY_FN() {
	_MESSAGE="AUX3 status"
	_PENTAIR_CMD="#AUX3 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX3_ON_FN() {
	_MESSAGE="Turning AUX3 ON"
	_PENTAIR_CMD="#AUX3 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX3_OFF_FN() {
	_MESSAGE="Turning AUX3 OFF"
	_PENTAIR_CMD="#AUX3 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX4 List
_AUX4_QUERY_FN() {
	_MESSAGE="AUX4 status"
	_PENTAIR_CMD="#AUX4 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX4_ON_FN() {
	_MESSAGE="Turning AUX4 ON"
	_PENTAIR_CMD="#AUX4 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX4_OFF_FN() {
	_MESSAGE="Turning AUX4 OFF"
	_PENTAIR_CMD="#AUX4 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX5 List
_AUX5_QUERY_FN() {
	_MESSAGE="AUX5 status"
	_PENTAIR_CMD="#AUX5 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX5_ON_FN() {
	_MESSAGE="Turning AUX5 ON"
	_PENTAIR_CMD="#AUX5 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX5_OFF_FN() {
	_MESSAGE="Turning AUX5 OFF"
	_PENTAIR_CMD="#AUX5 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX6 List
_AUX6_QUERY_FN() {
	_MESSAGE="AUX6 status"
	_PENTAIR_CMD="#AUX6 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX6_ON_FN() {
	_MESSAGE="Turning AUX6 ON"
	_PENTAIR_CMD="#AUX6 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX6_OFF_FN() {
	_MESSAGE="Turning AUX6 OFF"
	_PENTAIR_CMD="#AUX6 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX7 List
_AUX7_QUERY_FN() {
	_MESSAGE="AUX7 status"
	_PENTAIR_CMD="#AUX7 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX7_ON_FN() {
	_MESSAGE="Turning AUX7 ON"
	_PENTAIR_CMD="#AUX7 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX7_OFF_FN() {
	_MESSAGE="Turning AUX7 OFF"
	_PENTAIR_CMD="#AUX7 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX8 List
_AUX8_QUERY_FN() {
	_MESSAGE="AUX8 status"
	_PENTAIR_CMD="#AUX8 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX8_ON_FN() {
	_MESSAGE="Turning AUX8 ON"
	_PENTAIR_CMD="#AUX8 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX8_OFF_FN() {
	_MESSAGE="Turning AUX8 OFF"
	_PENTAIR_CMD="#AUX8 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX9 List
_AUX9_QUERY_FN() {
	_MESSAGE="AUX9 status"
	_PENTAIR_CMD="#AUX9 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX9_ON_FN() {
	_MESSAGE="Turning AUX9 ON"
	_PENTAIR_CMD="#AUX9 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX9_OFF_FN() {
	_MESSAGE="Turning AUX9 OFF"
	_PENTAIR_CMD="#AUX9 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX10 List
_AUX10_QUERY_FN() {
	_MESSAGE="AUX10 status"
	_PENTAIR_CMD="#AUX10 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX10_ON_FN() {
	_MESSAGE="Turning AUX10 ON"
	_PENTAIR_CMD="#AUX10 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX10_OFF_FN() {
	_MESSAGE="Turning AUX10 OFF"
	_PENTAIR_CMD="#AUX10 =0<cr>"
	_SERIAL_CMD_FN
}
