#!/bin/bash

# AUX41 List
_AUX41_QUERY_FN() {
	_MESSAGE="AUX41 status"
	_PENTAIR_CMD="#AUX41 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX41_ON_FN() {
	_MESSAGE="Turning AUX41 ON"
	_PENTAIR_CMD="#AUX41 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX41_OFF_FN() {
	_MESSAGE="Turning AUX41 OFF"
	_PENTAIR_CMD="#AUX41 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX42 List
_AUX42_QUERY_FN() {
	_MESSAGE="AUX42 status"
	_PENTAIR_CMD="#AUX42 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX42_ON_FN() {
	_MESSAGE="Turning AUX42 ON"
	_PENTAIR_CMD="#AUX42 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX42_OFF_FN() {
	_MESSAGE="Turning AUX42 OFF"
	_PENTAIR_CMD="#AUX42 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX43 List
_AUX43_QUERY_FN() {
	_MESSAGE="AUX43 status"
	_PENTAIR_CMD="#AUX43 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX43_ON_FN() {
	_MESSAGE="Turning AUX43 ON"
	_PENTAIR_CMD="#AUX43 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX43_OFF_FN() {
	_MESSAGE="Turning AUX43 OFF"
	_PENTAIR_CMD="#AUX43 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX44 List
_AUX44_QUERY_FN() {
	_MESSAGE="AUX44 status"
	_PENTAIR_CMD="#AUX44 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX44_ON_FN() {
	_MESSAGE="Turning AUX44 ON"
	_PENTAIR_CMD="#AUX44 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX44_OFF_FN() {
	_MESSAGE="Turning AUX44 OFF"
	_PENTAIR_CMD="#AUX44 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX45 List
_AUX45_QUERY_FN() {
	_MESSAGE="AUX45 status"
	_PENTAIR_CMD="#AUX45 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX45_ON_FN() {
	_MESSAGE="Turning AUX45 ON"
	_PENTAIR_CMD="#AUX45 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX45_OFF_FN() {
	_MESSAGE="Turning AUX45 OFF"
	_PENTAIR_CMD="#AUX45 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX46 List
_AUX46_QUERY_FN() {
	_MESSAGE="AUX46 status"
	_PENTAIR_CMD="#AUX46 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX46_ON_FN() {
	_MESSAGE="Turning AUX46 ON"
	_PENTAIR_CMD="#AUX46 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX46_OFF_FN() {
	_MESSAGE="Turning AUX46 OFF"
	_PENTAIR_CMD="#AUX46 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX47 List
_AUX47_QUERY_FN() {
	_MESSAGE="AUX47 status"
	_PENTAIR_CMD="#AUX47 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX47_ON_FN() {
	_MESSAGE="Turning AUX47 ON"
	_PENTAIR_CMD="#AUX47 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX47_OFF_FN() {
	_MESSAGE="Turning AUX47 OFF"
	_PENTAIR_CMD="#AUX47 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX48 List
_AUX48_QUERY_FN() {
	_MESSAGE="AUX48 status"
	_PENTAIR_CMD="#AUX48 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX48_ON_FN() {
	_MESSAGE="Turning AUX48 ON"
	_PENTAIR_CMD="#AUX48 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX48_OFF_FN() {
	_MESSAGE="Turning AUX48 OFF"
	_PENTAIR_CMD="#AUX48 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX49 List
_AUX49_QUERY_FN() {
	_MESSAGE="AUX49 status"
	_PENTAIR_CMD="#AUX49 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX49_ON_FN() {
	_MESSAGE="Turning AUX49 ON"
	_PENTAIR_CMD="#AUX49 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX49_OFF_FN() {
	_MESSAGE="Turning AUX49 OFF"
	_PENTAIR_CMD="#AUX49 =0<cr>"
	_SERIAL_CMD_FN
}
# AUX50 List
_AUX50_QUERY_FN() {
	_MESSAGE="AUX50 status"
	_PENTAIR_CMD="#AUX50 ?<cr>"
	_SERIAL_CMD_FN
}
_AUX50_ON_FN() {
	_MESSAGE="Turning AUX50 ON"
	_PENTAIR_CMD="#AUX50 =1<cr>"
	_SERIAL_CMD_FN
}
_AUX50_OFF_FN() {
	_MESSAGE="Turning AUX50 OFF"
	_PENTAIR_CMD="#AUX50 =0<cr>"
	_SERIAL_CMD_FN
}
